import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import { getOptions } from "@/features/setting/actions/setting-action";
import { Setting } from "@/features/core/types/app";
import { defaultSetting } from "@/features/core/data/default-setting";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const getSetting = async () => {
    const res = await getOptions([], ['theme', 'default_language']);
    return res;
  }

  const setting = await getSetting();
  
  return (
    <html lang={setting.general.default_language} className={setting.appearances.theme}>
      <body
        className={`antialiased min-h-screen`}
      >
        <Providers setting={setting as Setting}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
