import type { Metadata } from "next";
import "./globals.css";
import { getOptions } from "@/features/setting/actions/setting-action";
import { Providers } from "./providers";
import { Setting } from "@/features/core/types/app";
import { ThemeProvider } from 'next-themes'
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from "next-intl";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const getSetting = async () => {
    const res = await getOptions([], ['theme', 'default_language']);
    return res;
  }

  const setting = await getSetting();
  const messages = await getMessages();

  return (
    <html suppressHydrationWarning>
      <body
        className={`antialiased min-h-screen`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme={setting.appearances.theme as string}
            enableSystem
            disableTransitionOnChange
          >
            <Providers setting={setting as Setting}>
              {children}
            </Providers>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
